0.4.0 schema resdesign fermentcat test data
openownership/data-standard pull request #564
Opened 2024-02-29 10:24 UTC by BibianaC

Added more valid test data.

2024-03-04 16:12 UTC, rhiaro requested changes
These don't validate when I run `pytest tests/test_data.py`, can you have a look at what might be wrong?

2024-03-05 09:47 UTC, BibianaC commented
@rhiaro were the previous test documents (the ones already merged) passing the validation?

2024-03-05 10:46 UTC, rhiaro commented
@BibianaC No, there were a few validation errors which I [fixed](https://github.com/openownership/data-standard/pull/564/commits/4eca64a3f41f59a293ff6eb197c38d253b8eb269) to get it merged.

In this case, at least one of the files doesn't even parse as valid JSON - let me know if you want to look through the errors together.

2024-03-06 17:13 UTC, rhiaro approved these changes

2024-03-06 17:14 UTC, merged