Docs dates page
openownership/data-standard pull request #634
Opened 2024-04-11 15:49 UTC by kathryn-ods

# Overview

- What does this pull request do? creates a new page for dates guidance
- How can a reviewer test or examine your changes? build the docs and look through the page 
- Who is best placed to review it? @kd-ods 

Closes #

## Translations

- [ ] New or edited strings appearing as a result of this PR will be picked up for translation
- [ ] I've notified the translation coordinator of any new strings that will need
      translating. See: https://openownership.github.io/bods-dev-handbook/translations.html

## Documentation & Release

- [x] I've checked that the documentation builds without failing. See: https://github.com/openownership/data-standard#building-the-documentation-locally
- [ ] I've thought about how and when this needs to be released. See:
      https://openownership.github.io/bods-dev-handbook/standard_releases.html      
- [ ] I've updated the changelog, if necessary.
- [ ] I've updated [reference.rst](https://standard.openownership.org/en/latest/schema/reference.html) to reflect any changes to schema structure or naming.
- [ ] I've added or edited any other related documentation. See: https://github.com/openownership/bods-dev-handbook/blob/master/style_guide.md

2024-04-15 14:01 UTC, kd-ods requested changes
I think this page works really well and should be super helpful to publishers! And nice work on the diagrams :-)

Just a few things to take a look at.

2024-04-15 17:00 UTC, kathryn-ods commented
@kd-ods have made those changes

2024-04-16 12:03 UTC, kd-ods requested changes
Apologies! I introduced a few errors in my suggestions. Take a look.

2024-04-16 12:03 UTC, kd-ods commented on docs/schema/guidance/dates-guidance.rst
> +Due to an error in the publication system, a relationship statement is published with an incorrect `interest.startDate`. To correct this, a new statement is published replacing the incorrect one.
```suggestion
Due to an error in the publication system, a relationship statement is published with an incorrect ``interest.startDate``. To correct this, a new statement is published replacing the incorrect one. 
```

2024-04-16 12:03 UTC, kd-ods commented on docs/schema/guidance/dates-guidance.rst
> +* has the same `statementDate`, because the date of the original information submission has not changed
```suggestion
* has the same ``statementDate``, because the date of the original information submission has not changed
```

2024-04-16 12:03 UTC, kd-ods commented on docs/schema/guidance/dates-guidance.rst
> +* has a new `publicationDate`
```suggestion
* has a new ``publicationDate``
```

2024-04-16 12:03 UTC, kd-ods commented on docs/schema/guidance/dates-guidance.rst
> +* has a corrected `interest.startDate`
```suggestion
* has a corrected ``interest.startDate``
```

2024-04-16 14:32 UTC, kathryn-ods commented on docs/schema/guidance/dates-guidance.rst
> +Where rounded dates are used this should be noted in the publisher’s accompanying guidance for data users. `See building an auditable record of beneficial ownership <https://www.openownership.org/en/
@kd-ods how about 'Publishers SHOULD create accompanying guidance for data users.' Or I'd have recommend lower case

2024-04-16 14:32 UTC, kathryn-ods commented
@kd-ods I've changed those and done another check through of the build :)

2024-04-16 16:48 UTC, kd-ods approved these changes
Great!

2024-04-16 16:51 UTC, merged