Kathryn ods patch 1
openownership/data-standard pull request #723
Opened 2024-08-14 14:29 UTC by kathryn-ods

# Overview

**What does this pull request do?**
updates example data - componentRecords fields were listing statementIds, now they list recordIds

**How can a reviewer test or examine your changes?**

**Who is best placed to review it?**

Closes #

## Translations

- [ ] New or edited strings appearing as a result of this PR will be picked up for translation
- [ ] I've notified the translation coordinator of any new strings that will need
      translating. [See the Handbook](https://openownership.github.io/bods-dev-handbook/translations.html)

## Documentation & Release

- [ ] I've checked that the documentation builds without failing. [See the Handbook](https://github.com/openownership/data-standard#building-the-documentation-locally)
- [ ] I've thought about how and when this needs to be released. [See the Handbook](https://openownership.github.io/bods-dev-handbook/standard_releases.html)      
- [ ] I've updated the changelog, if necessary. [See the Handbook](https://openownership.github.io/bods-dev-handbook/standard_releases.html#changelog)
- [ ] I've updated [reference.rst](https://standard.openownership.org/en/latest/schema/reference.html) to reflect any changes to schema structure or naming.
- [ ] I've added or edited any other related documentation. [See the Handbook](https://github.com/openownership/bods-dev-handbook/blob/master/style_guide.md)

2024-08-23 14:57 UTC, kd-ods commented
@kathryn-ods - you can remove your changes to examples/bods-package-fi-soe.json from this PR, since I fixed the component recordId in PR #727

2024-09-03 13:42 UTC, kathryn-ods commented
> @kathryn-ods - you can remove your changes to examples/bods-package-fi-soe.json from this PR, since I fixed the component recordId in PR #727

Have done this now and re-requested a review

2024-09-03 14:14 UTC, kathryn-ods commented
having an issue with the link check tests - https://www.iso20022.org/market-identifier-codes showing as broken

2024-09-03 14:24 UTC, kathryn-ods commented
ok I removed and readded the link and that seems to have worked

2024-09-03 16:39 UTC, kd-ods commented
@kathryn-ods - I'll take a look at this Wed.

2024-09-09 17:07 UTC, kd-ods requested changes
A couple of the example files could do with checking again. 

It's a headache getting these componentRecords lists right.

2024-09-12 11:10 UTC, kathryn-ods commented on examples/mutilple-indirect-ownership-2.json
> +        "1e049760d6c7",
Thanks Kadie - I mapped them out in Miro to confirm these and your edits are right  https://miro.com/app/board/uXjVLfqBOP8=/?share_link_id=907051498258

2024-12-19 15:56 UTC, kathryn-ods commented
@kd-ods I think this is out of date now? These changes should have been made in the other PR

2024-12-19 15:56 UTC, closed without merging